//! Putting the terminal into the state a viewer needs, and reliably putting it back.

//! Gated to unix by its parent, not by an inner attribute: an empty module
//! whose users still name its types is a compile error somewhere confusing,
//! rather than a missing feature somewhere obvious.

use std::io::Write;
use std::os::fd::{AsRawFd, RawFd};

// Every sequence this module writes, in one place. They are generated by the
// viewer and never relayed from the box (see [`super::kitty`]).
const ALT_SCREEN_ON: &str = "\x1b[?1049h";
const ALT_SCREEN_OFF: &str = "\x1b[?1049l";
const CURSOR_HIDE: &str = "\x1b[?25l";
const CURSOR_SHOW: &str = "\x1b[?25h";
/// Any-motion tracking plus SGR coordinates. Any-motion, not button-only,
/// because hover is load-bearing on the web: menus open on it and a viewer
/// without it cannot drive most navigation. SGR because the original encoding
/// packs coordinates into single bytes and silently stops above column 223.
const MOUSE_ON: &str = "\x1b[?1003h\x1b[?1006h";
const MOUSE_OFF: &str = "\x1b[?1003l\x1b[?1006l";
/// Bracketed paste, so a pasted string arrives as one event. Without it a
/// paste is indistinguishable from very fast typing, and any control byte in
/// the pasted text would be read as a viewer command.
const PASTE_ON: &str = "\x1b[?2004h";
const PASTE_OFF: &str = "\x1b[?2004l";

/// The terminal's dimensions, in cells and in pixels.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Size {
    pub cols: u16,
    pub rows: u16,
    /// One cell's width in pixels, or 0 when the terminal will not say.
    pub cell_w: u16,
    pub cell_h: u16,
}

/// Ask the terminal how big it is.
///
/// `TIOCGWINSZ` reports the window in pixels as well as in cells, which is the
/// only portable way to learn a cell's pixel size, and without that the image
/// cannot be given a cell box that preserves its aspect ratio. Terminals that
/// leave the pixel fields at zero are handled by the caller
/// ([`super::image::fit`]), not papered over here.
pub fn size(fd: RawFd) -> Size {
    let mut ws: libc::winsize = unsafe { std::mem::zeroed() };
    if unsafe { libc::ioctl(fd, libc::TIOCGWINSZ, &mut ws) } != 0 {
        return Size::default();
    }
    Size {
        cols: ws.ws_col,
        rows: ws.ws_row,
        cell_w: ws.ws_xpixel.checked_div(ws.ws_col).unwrap_or(0),
        cell_h: ws.ws_ypixel.checked_div(ws.ws_row).unwrap_or(0),
    }
}

impl Size {
    /// A geometry that can actually be drawn in, even when the terminal will not say what its
    /// own is.
    pub fn or_fallback(self) -> Size {
        Size {
            cols: if self.cols == 0 { 80 } else { self.cols },
            rows: if self.rows == 0 { 24 } else { self.rows },
            cell_w: if self.cell_w == 0 { 8 } else { self.cell_w },
            cell_h: if self.cell_h == 0 { 16 } else { self.cell_h },
        }
    }
}

/// Is this file descriptor a terminal at all?
pub fn is_tty(fd: RawFd) -> bool {
    unsafe { libc::isatty(fd) == 1 }
}

/// Wait until `fd` has input, or the timeout expires.
///
/// The render loop needs to do things on a clock (refresh the status line,
/// notice a resize, notice that another process took the control lock) so it
/// cannot simply block on a read. Returns true when there is input to read.
pub fn wait_readable(fd: RawFd, timeout: std::time::Duration) -> bool {
    let mut pfd = libc::pollfd {
        fd,
        events: libc::POLLIN,
        revents: 0,
    };
    let ms = timeout.as_millis().min(i32::MAX as u128) as i32;
    unsafe { libc::poll(&mut pfd, 1, ms) > 0 }
}

/// The terminal's saved state, restored on drop.
pub struct Guard {
    fd: RawFd,
    saved: libc::termios,
    mouse: bool,
}

impl Guard {
    /// Enter raw mode on the alternate screen.
    ///
    /// Raw mode disables the signal characters too, so `Ctrl-C` becomes a
    /// keystroke rather than a signal. That is required, a page under test may
    /// well bind it, and it is why the viewer must always keep a key of its
    /// own that leaves ([`super::input`]).
    pub fn enter(fd: RawFd) -> std::io::Result<Guard> {
        if !is_tty(fd) {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Unsupported,
                "not a terminal",
            ));
        }
        let mut saved: libc::termios = unsafe { std::mem::zeroed() };
        if unsafe { libc::tcgetattr(fd, &mut saved) } != 0 {
            return Err(std::io::Error::last_os_error());
        }
        let mut raw = saved;
        unsafe { libc::cfmakeraw(&mut raw) };
        // Block until at least one byte, with no inter-byte timer: the loop
        // does its own waiting through `wait_readable`, so a read only happens
        // when there is something to read.
        raw.c_cc[libc::VMIN] = 1;
        raw.c_cc[libc::VTIME] = 0;
        if unsafe { libc::tcsetattr(fd, libc::TCSANOW, &raw) } != 0 {
            return Err(std::io::Error::last_os_error());
        }

        let mut out = std::io::stdout();
        let _ = write!(out, "{ALT_SCREEN_ON}{CURSOR_HIDE}{PASTE_ON}");
        let _ = out.flush();
        Ok(Guard {
            fd,
            saved,
            mouse: false,
        })
    }

    /// Take the mouse for the page, or give it back to the terminal.
    ///
    /// Idempotent, because the caller flips this on every mode change and
    /// re-sending the sequences on each frame would be noise on the wire.
    pub fn set_mouse(&mut self, on: bool) {
        if self.mouse == on {
            return;
        }
        self.mouse = on;
        let mut out = std::io::stdout();
        let _ = out.write_all(if on { MOUSE_ON.as_bytes() } else { MOUSE_OFF.as_bytes() });
        let _ = out.flush();
    }

    pub fn size(&self) -> Size {
        size(self.fd)
    }
}

impl Drop for Guard {
    fn drop(&mut self) {
        // Every mode this guard turned on, turned off. In the reverse order,
        // and unconditionally. A `?` anywhere in here would be a terminal left
        // broken because the restore itself had a bad day.
        let mut out = std::io::stdout();
        if self.mouse {
            let _ = out.write_all(MOUSE_OFF.as_bytes());
        }
        let _ = write!(out, "{PASTE_OFF}{CURSOR_SHOW}{ALT_SCREEN_OFF}");
        let _ = out.flush();
        unsafe { libc::tcsetattr(self.fd, libc::TCSANOW, &self.saved) };
    }
}

/// Read whatever is available on `fd` right now, appending to `buf`.
///
/// Returns the number of bytes read; 0 means end of input. `EINTR` reads as
/// "nothing this time" rather than as an error, because a window resize
/// interrupts the read and that is an ordinary event, not a failure.
pub fn read_available(fd: RawFd, buf: &mut Vec<u8>) -> std::io::Result<usize> {
    let mut scratch = [0u8; 4096];
    let n = unsafe { libc::read(fd, scratch.as_mut_ptr().cast(), scratch.len()) };
    if n < 0 {
        let err = std::io::Error::last_os_error();
        if err.kind() == std::io::ErrorKind::Interrupted {
            return Ok(0);
        }
        return Err(err);
    }
    buf.extend_from_slice(&scratch[..n as usize]);
    Ok(n as usize)
}

/// stdin's descriptor, as the viewer uses it.
pub fn stdin_fd() -> RawFd {
    std::io::stdin().as_raw_fd()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_pipe_is_not_a_terminal_and_the_guard_refuses_it() {
        // `h5i box view --term | tee log` has to fail with a sentence, not by
        // writing escape sequences into a file and hanging on a read.
        let mut fds = [0i32; 2];
        assert_eq!(unsafe { libc::pipe(fds.as_mut_ptr()) }, 0);
        assert!(!is_tty(fds[0]));
        let err = match Guard::enter(fds[0]) {
            Err(e) => e,
            Ok(_) => panic!("a pipe must not be put into raw mode"),
        };
        assert_eq!(err.kind(), std::io::ErrorKind::Unsupported);
        // And size degrades to zeroes rather than to garbage.
        assert_eq!(size(fds[0]), Size::default());
        unsafe {
            libc::close(fds[0]);
            libc::close(fds[1]);
        }
    }

    #[test]
    fn waiting_on_a_quiet_descriptor_times_out_rather_than_blocking() {
        let mut fds = [0i32; 2];
        assert_eq!(unsafe { libc::pipe(fds.as_mut_ptr()) }, 0);
        let started = std::time::Instant::now();
        assert!(!wait_readable(fds[0], std::time::Duration::from_millis(20)));
        assert!(started.elapsed() < std::time::Duration::from_secs(2));

        // And returns promptly once there is something to read.
        assert_eq!(unsafe { libc::write(fds[1], b"x".as_ptr().cast(), 1) }, 1);
        assert!(wait_readable(fds[0], std::time::Duration::from_secs(1)));
        let mut buf = Vec::new();
        assert_eq!(read_available(fds[0], &mut buf).unwrap(), 1);
        assert_eq!(buf, b"x");
        unsafe {
            libc::close(fds[0]);
            libc::close(fds[1]);
        }
    }

    #[test]
    fn a_terminal_that_reports_no_size_still_gets_a_drawable_one() {
        // A pty opened without a window size reports zeroes, and `TIOCGWINSZ`
        // succeeds while doing it. Taken literally the viewer scales the page
        // into one cell and draws a single pixel, with no error anywhere,
        // which is exactly what it did under `script` against a live box.
        let none = Size::default().or_fallback();
        assert_eq!((none.cols, none.rows), (80, 24));
        assert_eq!((none.cell_w, none.cell_h), (8, 16));

        // A terminal that reports cells but not pixels is the common case, and
        // only the cell size is filled in.
        let cells_only = Size {
            cols: 120,
            rows: 40,
            cell_w: 0,
            cell_h: 0,
        }
        .or_fallback();
        assert_eq!((cells_only.cols, cells_only.rows), (120, 40));
        assert_eq!((cells_only.cell_w, cells_only.cell_h), (8, 16));

        // A terminal that answers fully is left alone.
        let full = Size {
            cols: 100,
            rows: 30,
            cell_w: 9,
            cell_h: 18,
        };
        assert_eq!(full.or_fallback(), full);
    }

    #[test]
    fn end_of_input_reads_as_zero_rather_than_as_an_error() {
        let mut fds = [0i32; 2];
        assert_eq!(unsafe { libc::pipe(fds.as_mut_ptr()) }, 0);
        unsafe { libc::close(fds[1]) };
        let mut buf = Vec::new();
        assert_eq!(read_available(fds[0], &mut buf).unwrap(), 0);
        unsafe { libc::close(fds[0]) };
    }
}
